[package]
name = "lrwn"
description = "Library for encoding / decoding LoRaWAN frames."
homepage = "https://www.chirpstack.io"
license = "MIT"
version = "4.0.0-rc.3"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
repository = "https://github.com/chirpstack/chirpstack"

[dependencies]
hex = "0.4"
cmac = "0.6"
aes = "0.7"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "2.0.0-rc.1", features = [ "postgres" ] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Misc
lazy_static = "1.4"
